from __future__ import annotations

import argparse

from .page_mechanics import launch_mechanics_window


def _parse_args():
    p = argparse.ArgumentParser(description="EFTX Mechanical Modeler")
    p.add_argument("--runtime-json", default="", help="Optional runtime payload JSON generated by the legacy mechanical tab.")
    return p.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    launch_mechanics_window(runtime_payload_path=str(args.runtime_json or ""))
